# Navigation menus

[[main]]
  name = "Docs"
  weight = 10
  url = "/docs/"

[[main]]
  name = "GitHub"
  weight = 100
  url = "https://github.com/gedin-eth/sui-docs"
  pre = "<i class='fab fa-github'></i>"
